version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api: 
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./turbo.json:/app/turbo.json
      - api_node_modules:/app/apps/api/node_modules
      - shared_node_modules:/app/node_modules
    ports: 
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://taskuser:taskpass@postgres:5432/taskdb
    depends_on:
      - postgres

  webapp:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./turbo.json:/app/turbo.json
      - web_node_modules:/app/apps/web/node_modules
      - shared_node_modules:/app/node_modules
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  postgres_data:
  api_node_modules:
  web_node_modules:
  shared_node_modules: