version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api: 
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports: 
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://taskuser:taskpass@postgres:5432/taskdb
    depends_on:
      - postgres

  webapp:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      VITE_API_BASE_URL: http://api:3000

volumes:
  postgres_data: